config/routes.rb
Rails.application.routes.draw do

  get 'orders/show'
  get 'items/catalog'
  resources :charges

  root 'home#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get '/catalog', to: 'items#catalog'
  get '/new_collection', to: 'home#new_collection'

  get '/cart', to: 'carts#show'
  get '/checkout', to: 'orders#show'
  get '/signup', to: 'home#signup'
  get '/profil', to: 'home#profil'
  get '/edit_profil', to: 'home#edit_profil'
  get '/confirmation', to: 'home#confirmation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

#get '/product_europeen', to: 'home#product_europeen'
#get '/product_siberien', to: 'home#product_siberien'
#get '/product_persan', to: 'home#product_persan'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items

  def add_item(item_params)

    current_item = cart_items.find_by(item_id: item_params[:item][:item_id])

    if current_item
      current_item.quantity += item_params[:item][:quantity].to_i
      current_item.save
    else
      new_item = cart_items.create(item_id: item_params[:item][:item_id],
        quantity: item_params[:item][:quantity],
        cart_id: self.id)

      end
      new_item
    end

    def total
        cart_items.to_a.sum(&:total)
    end
  end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item

  def total
    item.price * quantity  
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items
  validates :title, presence: {message: "Veuillez donner un titre"}, length: {minimum: 2}
  validates :price, presence: {message: "Veuillez renseigner un prix"}
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
  
  validates :title, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :title, uniqueness: { case_sensitive: false }
  validates :image_url,
    format: {
      with: /\.(jpg|png|gif)\z/i,
      message: "must be in jpg, png or gif format"
    },
    allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    after_create  :welcome_email, :cart_creation

    def welcome_email
       @user = self.email
      TestMailer.with(user: @user).test_email.deliver_now
    end

    def cart_creation
      Cart.create(user_id: self.id)
    end

    # private
    #   def user_params
    #     params.require(:user).permit(:email)
    #   end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def profil
  end

  def signup
  end

  def product_europeen
  end

  def product_siberien
  end

  def product_persan
  end
  def new_collection
  end
  def confirmation
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render "layouts/header"%>

<body class="ecommerce">
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->
  <div class="wrapper">
    <!-- Start Site Content -->
    <div class="site-content ptb-100">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <!-- Start Content Area -->
            <div id="primary" class="content-area">
              <div class="row">
                <div class="col-xs-12 col-sm-9 col-md-9">
                  <!-- Start Table -->
                  <div class="table-responsive">
                    <table class="table-condensed table-bordered cart-table">
                      <thead>
                        <tr>
                          <th class="cart-iremove">Remove</th>
                          <th class="cart-ithumbnail">Product</th>
                          <th class="cart-iname">Product Name</th>
                          <th class="cart-iprice">Price</th>
                          <th class="cart-iquantity">Quantity</th>
                          <th class="cart-itotal">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td class="cart-iremove"><a href="#"><i class="icofont icofont-close"></i></a></td>
                          <td class="cart-ithumbnail"><a href="#"><img alt="" src="img/products/cart-1.jpg"></a></td>
                          <td class="cart-iname"><a href="#">Picture</a></td>
                          <td class="cart-iprice">€ 99.00</td>
                          <td class="cart-iquantity">01</td>
                          <td class="cart-itotal">€ 99.00</td>
                        </tr>
                        <tr>
                          <td class="cart-iremove"><a href="#"><i class="icofont icofont-close"></i></a></td>
                          <td class="cart-ithumbnail"><a href="#"><img alt="" src="img/products/cart-2.jpg"></a></td>
                          <td class="cart-iname"><a href="#">Picture</a></td>
                          <td class="cart-iprice">€ 99.00</td>
                          <td class="cart-iquantity">01</td>
                          <td class="cart-itotal">€ 99.00</td>
                        </tr>
                        <tr>
                          <td class="cart-iremove"><a href="#"><i class="icofont icofont-close"></i></a></td>
                          <td class="cart-ithumbnail"><a href="#"><img alt="" src="img/products/cart-3.jpg"></a></td>
                          <td class="cart-iname"><a href="#">Picture</a></td>
                          <td class="cart-iprice">€ 99.00</td>
                          <td class="cart-iquantity">01</td>
                          <td class="cart-itotal">€ 99.00</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <!-- End Table -->
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3">
                  <!-- Start Cart Widget -->
                  <div class="cart-widget">
                    <!-- Start Copun -->
                    <div class="coupon-area mb-60">
                      <p class="uppercase"><strong>Have a coupon ?</strong></p>
                      <input type="text" placeholder="Enter your code">
                      <a class="btn btn-brown btn-flat btn-coupon">Submit</a>
                    </div>
                    <!-- End Copun -->
                    <p class="uppercase"><strong>Cart total</strong></p>
                    <!-- Start Table -->
                    <table class="table widget-table">
                      <tbody>
                        <tr>
                          <td>Cart Subtotal</td>
                          <td class="text-right">€ 99.00</td>
                        </tr>
                        <tr>
                          <td>Shipping</td>
                          <td class="text-right">Free</td>
                        </tr>
                        <tr>
                          <td>Grand Total</td>
                          <td class="text-right">€ 99.00</td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- End Table -->
                    <!-- Update Buttons -->
                    <div class="update-cart-area">
                      <a href="#" class="btn btn-brown btn-borders btn-flat">Update Cart</a>
                      <a href="checkout" class="btn btn-brown btn-flat pull-right">Order now</a>
                    </div>
                    <!-- End Update Buttons -->
                  </div>
                  <!-- End Cart Widget -->
                </div>
              </div>
            </div>
            <!-- End Content Area -->
          </div>
        </div>
      </div>
    </div>
    <!-- End Site Content -->

  </body>

  <%= render "layouts/footer"%>